/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaintegralcalculation;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author student_m
 */
public class JavaIntegralCalculation extends javax.swing.JFrame {

    /**
     * Creates new form JavaIntegralCalculation
     */
    public JavaIntegralCalculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldLowerLimit = new javax.swing.JTextField();
        jTextFieldUpperLimit = new javax.swing.JTextField();
        jTextFieldStep = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSaveText = new javax.swing.JMenuItem();
        jMenuItemLoadText = new javax.swing.JMenuItem();
        jMenuItemSaveBinary = new javax.swing.JMenuItem();
        jMenuItemLoadBinary = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextFieldLowerLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLowerLimitActionPerformed(evt);
            }
        });

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Upper limit");

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Lower limit");

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Step");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldLowerLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUpperLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLowerLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUpperLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(204, 255, 255))); // NOI18N
        jPanel2.setToolTipText("");

        jButtonAdd.setText("Add item");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete item");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCalculate.setText("Calculate");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setForeground(new java.awt.Color(204, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lower limit", "Upper limit", "Step", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(204, 0, 0));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonAdd)
                        .addGap(77, 77, 77)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCalculate)))
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCalculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItemSaveText.setText("save");
        jMenuItemSaveText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveTextActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSaveText);

        jMenuItemLoadText.setText("load");
        jMenuItemLoadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadTextActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLoadText);

        jMenuItemSaveBinary.setText("Save Binary");
        jMenuItemSaveBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveBinaryActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSaveBinary);

        jMenuItemLoadBinary.setText("Load Binary");
        jMenuItemLoadBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadBinaryActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLoadBinary);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLowerLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLowerLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLowerLimitActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        double upperLim;
    double lowLim;
    double step;

    try {
        lowLim = Double.parseDouble(jTextFieldLowerLimit.getText());
        upperLim = Double.parseDouble(jTextFieldUpperLimit.getText());
        step = Double.parseDouble(jTextFieldStep.getText());

        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

        tModel.addRow(new Object[]{lowLim, upperLim, step, ""});

        // Optional: clear fields after adding
        jTextFieldLowerLimit.setText("");
        jTextFieldUpperLimit.setText("");
        jTextFieldStep.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter valid numbers!");
    }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        
        int rowNum = jTable1.getSelectedRow();
        if (rowNum == -1){
            JOptionPane.showMessageDialog(null, "You need to select a row");
        }else{
            tModel.removeRow(rowNum);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        // TODO add your handling code here:
        int rowNum = jTable1.getSelectedRow();

    if (rowNum == -1) {
        JOptionPane.showMessageDialog(
                this,
                "You need to select a row"
        );
        return;
    }

    DefaultTableModel tModel =
            (DefaultTableModel) jTable1.getModel();

    double upperLim;
    double lowLim;
    double step;

    try {
        lowLim = Double.parseDouble(
                tModel.getValueAt(rowNum, 0).toString());

        upperLim = Double.parseDouble(
                tModel.getValueAt(rowNum, 1).toString());

        step = Double.parseDouble(
                tModel.getValueAt(rowNum, 2).toString());

    } catch (NumberFormatException ex) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter valid numbers."
        );
        return;
    }

    if (upperLim <= lowLim || step <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Upper limit must be greater than lower limit, "
                + "and step must be greater than 0."
        );
        return;
    }

    final int selectedRow = rowNum;

    Thread calculationThread = new Thread(() -> {

        final int NUMBER_OF_THREADS = 10;

        double interval = upperLim - lowLim;
        double partSize = interval / NUMBER_OF_THREADS;

        IntegralRunnable[] tasks =
                new IntegralRunnable[NUMBER_OF_THREADS];

        Thread[] threads =
                new Thread[NUMBER_OF_THREADS];

        for (int i = 0; i < NUMBER_OF_THREADS; i++) {

            double partLow =
                    lowLim + i * partSize;

            double partHigh;

            if (i == NUMBER_OF_THREADS - 1) {
                partHigh = upperLim;
            } else {
                partHigh =
                        lowLim + (i + 1) * partSize;
            }

            tasks[i] =
                    new IntegralRunnable(
                            partLow,
                            partHigh,
                            step
                    );

            threads[i] =
                    new Thread(
                            tasks[i],
                            "Integral Thread " + (i + 1)
                    );

            threads[i].start();
        }

        double result = 0.0;

        try {

            for (int i = 0; i < NUMBER_OF_THREADS; i++) {
                threads[i].join();
                result += tasks[i].getResult();
            }

            final double finalResult = result;

            javax.swing.SwingUtilities.invokeLater(() -> {

                DefaultTableModel model =
                        (DefaultTableModel) jTable1.getModel();

                model.setValueAt(
                        finalResult,
                        selectedRow,
                        3
                );

                JOptionPane.showMessageDialog(
                        this,
                        "Calculation completed using "
                        + NUMBER_OF_THREADS
                        + " threads."
                );
            });

        } catch (InterruptedException ex) {

            Thread.currentThread().interrupt();

            javax.swing.SwingUtilities.invokeLater(() -> {

                JOptionPane.showMessageDialog(
                        this,
                        "Calculation was interrupted."
                );
            });
        }

    }, "Integral Calculator");

    calculationThread.start();
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jMenuItemSaveTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveTextActionPerformed
        JFileChooser chooser = new JFileChooser();
    FileNameExtensionFilter filter =
            new FileNameExtensionFilter("Text files (*.txt)", "txt");
    chooser.setFileFilter(filter);

    if (chooser.showSaveDialog(this)
            != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    if (!file.getName().toLowerCase().endsWith(".txt")) {
        file = new File(file.getAbsolutePath() + ".txt");
    }

    try {
        WriteFile writer = new WriteFile();
        writer.saveTable(file, jTable1);

        JOptionPane.showMessageDialog(
                this, "Data saved successfully!");

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(
                this, "Error saving file: " + ex.getMessage());
    }
    }//GEN-LAST:event_jMenuItemSaveTextActionPerformed

    private void jMenuItemLoadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadTextActionPerformed
        JFileChooser chooser = new JFileChooser();
    FileNameExtensionFilter filter =
            new FileNameExtensionFilter("Text files (*.txt)", "txt");
    chooser.setFileFilter(filter);

    if (chooser.showOpenDialog(this)
            != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    try {
        ReadFile reader = new ReadFile();
        java.util.List<Object[]> rows = reader.loadTable(file);

        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Object[] row : rows) {
            model.addRow(row);
        }

        JOptionPane.showMessageDialog(
                this, "Data loaded successfully!");

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(
                this, "Error loading file: " + ex.getMessage());
    }
    }//GEN-LAST:event_jMenuItemLoadTextActionPerformed

    private void jMenuItemSaveBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveBinaryActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

    if (chooser.showSaveDialog(this)
            != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    if (!file.getName().toLowerCase().endsWith(".dat")) {
        file = new File(file.getAbsolutePath() + ".dat");
    }

    try {
        WriteBinaryFile writer = new WriteBinaryFile();
        writer.saveTable(file, jTable1);

        JOptionPane.showMessageDialog(
                this, "Binary data saved successfully!");

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(
                this, "Error saving binary file: "
                        + ex.getMessage());
    }
    }//GEN-LAST:event_jMenuItemSaveBinaryActionPerformed

    private void jMenuItemLoadBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadBinaryActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

    if (chooser.showOpenDialog(this)
            != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    try {
        ReadBinaryFile reader = new ReadBinaryFile();
        java.util.List<Object[]> rows =
                reader.loadTable(file);

        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Object[] row : rows) {
            model.addRow(row);
        }

        JOptionPane.showMessageDialog(
                this, "Binary data loaded successfully!");

    } catch (IOException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(
                this, "Error loading binary file: "
                        + ex.getMessage());
    }
    }//GEN-LAST:event_jMenuItemLoadBinaryActionPerformed

    public double CalcIntegral(double lowLim, double upLim, double step)
{
    double start = lowLim;
    double h;
    double sumS = 0;

    while (start < upLim) {
        h = Math.min(step, upLim - start);

        sumS += h * (Math.sin(start) + Math.sin(start + h)) / 2;

        start += h;
    }

    return sumS;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaIntegralCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaIntegralCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaIntegralCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaIntegralCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaIntegralCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLoadBinary;
    private javax.swing.JMenuItem jMenuItemLoadText;
    private javax.swing.JMenuItem jMenuItemSaveBinary;
    private javax.swing.JMenuItem jMenuItemSaveText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldLowerLimit;
    private javax.swing.JTextField jTextFieldStep;
    private javax.swing.JTextField jTextFieldUpperLimit;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
